version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: em-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_manager
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d employee_manager -p 5432" ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - demo-network

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: employee-manager-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/employee_manager
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
